import Head from "next/head"
import Link from "next/link"
import Image from "next/image"


export default function ManchesterUnited() {

  
    return (
      <div className="h-full bg-stone-950 overflow-auto">
        <Head>
          <title>Photography Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/camera.png" />
        </Head>
  
        <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
          <span className="uppercase text-lg font-large">
            Arnav Karnik Photography
          </span>
          <Link href="/" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">
            Back to Portfolio
          </Link>
  
        </header>
  
        <main className="pt-[110px]"> 
        <div className="container mx-auto p-8 md:flex">


          <h1>Manchester United</h1>

</div>
        </main>
  
        
      </div>
      
    )
  }