import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import oldTrafford from "../..//public/structures/oldTraffordStadium.jpg"



export default function ManchesterUnited() {

  
    return (
      <div className="min-h-screen bg-stone-950 text-stone-100 overflow-auto">
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/camera.png" />
      </Head>

      {/* Header */}
      <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10 bg-stone-950/90 backdrop-blur-md shadow-md">
        <span className="uppercase text-xl font-semibold tracking-wide">
          Arnav Karnik Photography
        </span>
        <Link
          href="/"
          className="rounded-3xl bg-white text-stone-900 px-4 py-2 font-medium hover:bg-opacity-90 transition"
        >
          Back to Portfolio
        </Link>
      </header>

      {/* Hero Section */}
      <section className="relative w-full h-[60vh] pt-[90px]">
        <Image
          src={oldTrafford}
          alt="Old Trafford - The Theatre of Dreams"
          fill
          priority
          className="object-cover brightness-75"
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center text-center px-4">
          <h1 className="text-5xl md:text-6xl font-bold text-white drop-shadow-lg">
            Old Trafford
          </h1>
          <p className="mt-4 text-lg text-stone-200 max-w-2xl">
            The Theatre of Dreams
          </p>
        </div>
      </section>

      {/* Main Content */}
      <main className="pt-16 pb-20 px-6">
        <div className="container mx-auto max-w-3xl">
          <div className="bg-stone-900/60 backdrop-blur-md rounded-2xl shadow-lg p-8 space-y-6 text-center">
            <h2 className="text-3xl font-semibold tracking-tight text-white">
              Manchester United
            </h2>
            <p className="text-lg leading-relaxed text-stone-300">
              I became a United fan after watching{" "}
              <span className="italic">Bend It Like Beckham</span> when I was 8
              years old. I remember seeing the red Beckham jersey and knew
              Manchester United would be my team.
            </p>

            <p className="text-lg leading-relaxed text-stone-300">
              There have been a lot of ups and downs over the past couple of
              years, from Marcus Rashford incredible 22–23 season to losing
              against Tottenham in the Europa League final.
            </p>

            <p className="text-lg leading-relaxed text-stone-300">
              I am manifesting a successful future ahead of the upcoming season!
              Lets see if Ruben Amorim can turn the tide like he did at
              Sporting FC.
            </p>
          </div>
        </div>
      </main>
    </div>

      
    )
  }