import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import parisBasketball from "../..//public/structures/parisBasketball.jpg"


export default function ParisBasketball() {

  
    return (
      <div className="min-h-screen bg-stone-950 text-stone-100 overflow-auto">
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/camera.png" />
      </Head>

      {/* Header */}
      <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10 bg-stone-950/90 backdrop-blur-md shadow-md">
        <span className="uppercase text-xl font-semibold tracking-wide">
          Arnav Karnik Photography
        </span>
        <Link
          href="/"
          className="rounded-3xl bg-white text-stone-900 px-4 py-2 font-medium hover:bg-opacity-90 transition"
        >
          Back to Portfolio
        </Link>
      </header>

      {/* Hero Section */}
      <section className="relative w-full h-[60vh] pt-[90px]">
        <Image
          src={parisBasketball}
          alt="Hooping in Paris with Eiffel Tower"
          fill
          priority
          className="object-cover brightness-75"
        />
        <div className="absolute inset-0 flex flex-col items-center justify-center text-center px-4">
          <h1 className="text-5xl md:text-6xl font-bold text-white drop-shadow-lg">
            Hooping in Paris, France
          </h1>
          <p className="mt-4 text-lg text-stone-200 max-w-2xl">
            A basketball court beneath the Eiffel Tower – the perfect mix of
            sport and culture.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <main className="pt-16 pb-20 px-6">
        <div className="container mx-auto max-w-3xl">
          <div className="bg-stone-900/60 backdrop-blur-md rounded-2xl shadow-lg p-8 space-y-6">
            <h2 className="text-3xl font-semibold tracking-tight text-white text-center">
              Paris, France
            </h2>
            <p className="text-lg leading-relaxed text-stone-300">
              After eating ramen and visiting Parc des Princes, I was on my way
              back to my hotel when I heard some basketballs bouncing. I turned
              my head to the left and saw this stunning view — a bunch of guys
              playing ball with the Eiffel Tower in the background. I
              immediately took out my camera and started shooting away.
            </p>

            <p className="text-lg leading-relaxed text-stone-300">
              After packing up my camera and starting to walk back to my hotel,
              a thought crossed my mind:{" "}
              <span className="italic text-stone-100">
                “Wouldn’t it be sick to join the dudes on the court?”
              </span>{" "}
              So I did exactly that, playing four games until we lost. As I
              played, more and more people started to show up. The coolest part?
              They were only speaking French.
            </p>

            <p className="text-lg leading-relaxed text-stone-300">
              Arguing, bickering, and joking — all in French. I didn’t
              understand a word, but through basketball I could guess what was
              being said. It was my first experience truly seeing how sports
              transcend language barriers, and it amazed me!
            </p>

            <p className="text-lg leading-relaxed text-stone-300">
              I’m very happy I got to have this experience on such a beautiful
              court. Definitely the highlight of Paris for me.
            </p>
          </div>
        </div>
      </main>
    </div>
      
    )
  }