import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import profilePic from "../public/people/arnie.jpg"


export default function Home() {

  
    return (
      <div className="h-full bg-stone-950 overflow-auto">
        <Head>
          <title>Photography Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/camera.png" />
        </Head>
  
        <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
          <span className="uppercase text-lg font-large">
            Arnav Karnik Photography
          </span>
          <Link href="/" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">
            Back to Portfolio
          </Link>
  
        </header>
  
        <main className="pt-[110px]"> 

          <div className="container mx-auto p-8 md:flex">
            <div className="md:w-1/2 mb-4 md:mb-0 md:h-auto">
              <Image src={profilePic} alt="Your Picture" className="w-96 h-auto object-cover rounded" />
            </div>

            <div className="md:w-1/2 md:pl-8">
              <h2 className="text-2xl font-bold mb-4">Arnav Karnik</h2>
              <p>
                I am an aspiring photographer. I love exploring new places and capturing its beauty. 
                My portfolio showcases all my favorite pictures I have taken.
              </p><br></br>
              <p>
                This upcoming month I am traveling to India which I am escatic for. Stay tuned for some 
                India pictures!
              </p>
              <br/>
              <a href="https://www.instagram.com/arnavkarnikphotos/">Instagram</a><br/>
              <a href="mailto:arnavkarnikphotos@gmail.com">Contact Me</a>
            </div>
          </div>


        </main>
  
        
      </div>
      
    )
  }