import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import profilePic from "../public/people/arnie.jpg"


export default function Home() {

  
    return (
      <div className="h-full bg-stone-950 overflow-auto">
        <Head>
          <title>Photography Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/camera.png" />
        </Head>
  
        <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
          <span className="uppercase text-lg font-large">
            Arnav Karnik Photography
          </span>
          <Link href="/" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">
            Back to Portfolio
          </Link>
  
        </header>
  
        <main className="pt-[10px]">
            <div className="text-white-500 m-32 grid h-16 place-items-center">
                
                
                <span className="inline-grid grid-cols-2 gap-4">
                    <span>
                        <Image src={profilePic} alt="profile picture" className="rounded w-64 h-auto"/>
                    </span>
                    <span className="flex items-center justify-center">
                        <h1 className="text-lg">Arnav Karnik</h1>
                        <p className="text-white-600"></p>
                    </span>
                </span>
            </div>
        </main>
  
        
      </div>
      
    )
  }