import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import "@headlessui/react"

export default function Home() {
  return (
    <div className="h-full bg-stone-950">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between items-center h-[90px] px-6">
        <div className="text-transparent">hm</div>
        <div>Arnav Karnik Photography Portfolio</div>
        <Link href="#" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">
          Get in touch 
          </Link>

      </header>

      <main className="">
       <p>Placeholder for main</p>
      </main>

      <footer>
        <p>Placeholder for footer</p>
      </footer>
    </div>
    
  )
}