import Head from "next/head"
import Link from "next/link"
import {Tab} from "@headlessui/react"

export default function Home() {
  return (
    <div className="flex flex-col h-full bg-stone-950">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex justify-between items-center h-[90px] px-6">
        <div className="text-transparent">hm</div>
        <div>Arnav Karnik Photography Portfolio</div>
        <Link href="#" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">
          Get in touch 
          </Link>

      </header>

      <main className="grow">
        <div className="flex flex-col items-center">
          <Tab.Group>
            <Tab.List className="flex items-center gap-4">
              <Tab>All</Tab>
              <Tab>Landscapes</Tab>
              <Tab>People</Tab>
            </Tab.List>
            <Tab.Panels>
              <Tab.Panel>All Photos</Tab.Panel>
              <Tab.Panel>Landscapes</Tab.Panel>
              <Tab.Panel>People</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
    
      </main>

      <footer className="h-[60px]">
        <p>Placeholder for footer</p>
      </footer>
    </div>
    
  )
}