import Head from "next/head"
import Link from "next/link"

export default function Stories() {


    return (
        <div className="h-full bg-stone-950 overflow-auto">
        <Head>
            <title>Arnav's Photography Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/camera.png" />
        </Head>

        <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
            <span className="uppercase text-lg font-large">
            Arnav Karnik Photography
            </span>
            <Link href="/" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">
            Back to favorites
            </Link>

        </header>

        <main className="pt-[105px]">
            <div className="flex flex-col items-center h-full">
                <h1>Coming Soon ...</h1>
            </div>
        
        </main>

        <footer className="h-[90px] flex justify-center items-center uppercase text-lg font-medium">
            <p>Arnav Karnik Photography</p>
        </footer>
        </div>
        
    )
}