import { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { FaMapMarkerAlt } from 'react-icons/fa';  // Importing Font Awesome icon
import raigad from "../public/landscape/raigad.jpg"
import pelling from "../public/structures/pelling.jpg"
import kanchenjunga from "../public/landscape/khanchenjunga.jpg"
import buffalo from "../public/animals/buffalo.jpg"
import dotter from "../public/animals/dotter.jpg"
import elephants from "../public/animals/elephant.jpg"
import munnar from "../public/landscape/munnarTea.jpg"
import kolukkumalia from "../public/landscape/kolumkulai.jpg"
import sinhagad from "../public/structures/sinhagad.jpg"
import Image from 'next/image';

export default function Stories() {



    return (
        <div className="h-full bg-stone-950 overflow-auto">
            <Head>
                <title>Arnav's Photography Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/camera.png" />
            </Head>

            <header className="fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
                <span className="uppercase text-lg font-large text-white">
                    Arnav Karnik Photography
                </span>
                <Link href="/" className="rounded-3xl bg-white text-stone-900 px-3 py-2 hover:bg-opacity-90">
                    Back to favorites
                </Link>
            </header>

            <main className="pt-[105px]">
                <div className="flex flex-col items-center h-full">
                    <div
                        className="mt-5 cursor-pointer rounded-3xl bg-slate-400 text-stone-900 px-6 py-4 hover:bg-opacity-90 shadow-lg flex items-center justify-center space-x-3 w-80 h-40"
                    >
                      <a href='https://arnie12a.github.io/blog/india.html'>
                      <FaMapMarkerAlt className="text-red-500 text-2xl" />
                        <div>
                            <h2 className="text-xl font-semibold">India Trip</h2>
                            <p className="text-sm">Check out my favorite visits</p>
                        </div>
                      </a>
                        
                    </div>
                </div>
            </main>


            <footer className="h-[90px] flex justify-center items-center uppercase text-lg font-medium text-white">
                <p>Arnav Karnik Photography</p>
            </footer>
        </div>
    );
}
